[platformio]
default_envs = esp32dev-local

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
lib_deps =
    alphawallet/Web3E @ ^1.44
    adafruit/Adafruit PN532 @ ^1.3.4

[env:esp32dev-local]
build_flags =
    -DAPP_PROFILE_DEV_LOCAL

[env:esp32dev-testnet]
build_flags =
    -DAPP_PROFILE_TESTNET